version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_DATABASE: social-media-v2
  MYSQL_HOST: localhost
  MYSQL_ROOT_PASSWORD: root
services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./:/app
    expose:
      - 5000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 5000:5000
    links:
      - mysql
    command: npm run dev